### PR TITLE
Pages feature

### PR DESCRIPTION
**Pull request by claudiunicolaa**
Related to https://github.com/code4romania/monitorizare-vot-votanti-api/issues/21 and https://github.com/code4romania/monitorizare-vot-votanti-api/issues/22

* View all pages ***GET** /api/page[?limit=10]*

* Add new page ***POST** /api/page* with body 
```
{
    "title":"Titlu",
    "description": "Descriere",
    "status": "Active"
}
```
> The status field is optional and has two possible values: Active, Inactive. The default value is `Inactive`

* Edit page ***PUT** /api/page/{id}* with body
```
{
    "title":"Titlu",
    "description": "Descriere",
    "status": "Active"
}
```
> The status field is optional and has two possible values: Active, Inactive.

* Delete page ***DELETE** /api/page/{id}*

* Approve page ***POST** /api/page{id}/approve*

* Reject page ***POST** /api/page{id}/reject*

### CODE REVIEW

**Review by costeaalex — COMMENTED** [review]
Is there an issue for this merge request which outlines the requirements? I'm not sure what this feature is aiming to do.

**Comment by qwertypnk** [comment]
> Is there an issue for this merge request which outlines the requirements? I'm not sure what this feature is aiming to do.

It refers to:
https://github.com/code4romania/monitorizare-vot-votanti-api/issues/21
https://github.com/code4romania/monitorizare-vot-votanti-api/issues/22

It relates to:
https://github.com/code4romania/monitorizare-vot-votanti-admin/issues/16
https://github.com/code4romania/monitorizare-vot-votanti-admin/issues/17
https://github.com/code4romania/monitorizare-vot-votanti-admin/issues/18

I'm working on the admin features and I'll test them along with the branch for this pull request. I will accept the pull request if everything checks out.

**Comment by claudiunicolaa** [comment]
@qwertypnk Great! Tell me if you see something that requires some improvements.

**Comment by qwertypnk** [comment]
> @qwertypnk Great! Tell me if you see something that requires some improvements.

@claudiunicolaa The code looks really great. But I noticed a small improvement that can be made for Dingo API - see [https://github.com/dingo/api/issues/716](https://github.com/dingo/api/issues/716) - You can actually use $api->resource('page', 'App\Api\V1\Controllers\PageController') in api_routes.php instead of manually specifying the default resource routes for GET / POST / PUT / DELETE. This is obviously not necessary, but it would be a good example how to further handle resource controller routing. What do you think?

**Comment by claudiunicolaa** [comment]
> > @qwertypnk Great! Tell me if you see something that requires some improvements.
> 
> @claudiunicolaa The code looks really great. But I noticed a small improvement that can be made for Dingo API - see [dingo/api#716](https://github.com/dingo/api/issues/716) - You can actually use $api->resource('page', 'App\Api\V1\Controllers\PageController') in api_routes.php instead of manually specifying the default resource routes for GET / POST / PUT / DELETE. This is obviously not necessary, but it would be a good example how to further handle resource controller routing. What do you think?

Check out last commit https://github.com/code4romania/monitorizare-vot-votanti-api/pull/23/commits/b6aa7af57c6e0cfba6a00181368b9a9a084da0f8

**Comment by qwertypnk** [comment]
@claudiunicolaa merged

**Pull request merged**
